FROM almalinux:9






## FROM is the first instruction in a dockerfile...

## Command to build image from this dockerfile for local use:
## docker build -t <image_name> . 
## docker build -t <image_name>:<version> .

## If we use the above command again while pushing the image to dockerhub we have to add URL in the image or we can build it with URL 
## docker build -t <URL>/<user_name>/<image_name>:<version> .

## To push the local image to a Repository raname the image with URL:
## docker tag <existing_image>:<version> <URL>/<user_name>/<new_image_name>:<version> 
